apiVersion: v1
kind: Service
metadata:
  name: config-client-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-client-deployment
  labels:
    app: config-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-client
  template:
    metadata:
      labels:
        app: config-client
    spec:
      containers:
        - name: nginx
          image: modongsotay/config-client
          ports:
            - containerPort: 80